
services:
  backend:
    container_name: backend-container
    build:
      context: ./backend
      dockerfile: Dockerfile # Asegúrate de que el nombre del archivo sea correcto
    ports:
      - "5000:5000"
    networks:
      - presentacion-network
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb+srv://dbadmin:Jo12345678@presentaciondb.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000

#  frontend:
#    container_name: frontend-container
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    ports:
#      - "3000:80"
#    networks:
#      - presentacion-network
#    volumes:
      #- ./frontend:/app
#      - ./build:/usr/share/nginx/html
#    depends_on:
#      - backend

networks:
  presentacion-network:
    driver: bridge